from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)

from app.db.metadata import metadata


organization_runtime_profiles = Table(
    "organization_runtime_profiles",
    metadata,
    Column("organization_id", ForeignKey("campus_organizations.id", ondelete="CASCADE"), primary_key=True),
    Column("governance_mode", String(24), nullable=False, default="council"),
    Column("mission", Text, nullable=False, default=""),
    Column("reputation", Integer, nullable=False, default=50),
    Column("decision_delay_minutes", Integer, nullable=False, default=60),
    Column("quorum_weight", Integer, nullable=False, default=1),
    Column("metadata_json", Text, nullable=False, default="{}"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("governance_mode IN ('executive', 'council', 'consensus')", name="organization_profiles_governance_valid"),
    CheckConstraint("reputation BETWEEN 0 AND 100", name="organization_profiles_reputation_valid"),
    CheckConstraint("decision_delay_minutes >= 0", name="organization_profiles_delay_nonnegative"),
    CheckConstraint("quorum_weight > 0", name="organization_profiles_quorum_positive"),
)

organization_roles = Table(
    "organization_roles",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("organization_id", ForeignKey("campus_organizations.id", ondelete="CASCADE"), nullable=False),
    Column("role_key", String(80), nullable=False),
    Column("display_name", String(120), nullable=False),
    Column("permissions_json", Text, nullable=False, default="[]"),
    Column("spending_limit_minor", BigInteger, nullable=False, default=0),
    Column("vote_weight", Integer, nullable=False, default=1),
    Column("status", String(16), nullable=False, default="active"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("organization_id", "role_key", name="uq_organization_roles_org_key"),
    CheckConstraint("spending_limit_minor >= 0", name="organization_roles_limit_nonnegative"),
    CheckConstraint("vote_weight > 0", name="organization_roles_vote_positive"),
    CheckConstraint("status IN ('active', 'inactive')", name="organization_roles_status_valid"),
)

organization_role_assignments = Table(
    "organization_role_assignments",
    metadata,
    Column("organization_id", ForeignKey("campus_organizations.id", ondelete="CASCADE"), primary_key=True),
    Column("resident_id", ForeignKey("residents.id", ondelete="CASCADE"), primary_key=True),
    Column("role_id", ForeignKey("organization_roles.id", ondelete="RESTRICT"), nullable=False),
    Column("status", String(16), nullable=False, default="active"),
    Column("assigned_by_resident_id", ForeignKey("residents.id", ondelete="SET NULL")),
    Column("assigned_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("status IN ('active', 'inactive')", name="organization_assignments_status_valid"),
)

organization_proposals = Table(
    "organization_proposals",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("proposal_key", String(200), nullable=False, unique=True),
    Column("organization_id", ForeignKey("campus_organizations.id", ondelete="RESTRICT"), nullable=False),
    Column("proposer_resident_id", ForeignKey("residents.id", ondelete="RESTRICT"), nullable=False),
    Column("proposal_type", String(64), nullable=False),
    Column("title", String(200), nullable=False),
    Column("description", Text, nullable=False, default=""),
    Column("requested_budget_minor", BigInteger, nullable=False, default=0),
    Column("target_actor_key", String(120), nullable=False, default=""),
    Column("status", String(16), nullable=False, default="pending"),
    Column("approvals_required", Integer, nullable=False, default=1),
    Column("approvals_weight", Integer, nullable=False, default=0),
    Column("rejections_weight", Integer, nullable=False, default=0),
    Column("earliest_decision_at", String(64), nullable=False),
    Column("expires_at", String(64), nullable=False, default=""),
    Column("decision_reason", Text, nullable=False, default=""),
    Column("ledger_transaction_id", ForeignKey("ledger_transactions.id", ondelete="SET NULL")),
    Column("source_type", String(64), nullable=False, default="organization_runtime"),
    Column("source_id", String(120), nullable=False, default=""),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("decided_at", String(64), nullable=False, default=""),
    Column("executed_at", String(64), nullable=False, default=""),
    CheckConstraint("requested_budget_minor >= 0", name="organization_proposals_budget_nonnegative"),
    CheckConstraint("approvals_required > 0", name="organization_proposals_approvals_positive"),
    CheckConstraint("status IN ('pending', 'approved', 'rejected', 'executed', 'cancelled', 'expired')", name="organization_proposals_status_valid"),
)

organization_votes = Table(
    "organization_votes",
    metadata,
    Column("proposal_id", ForeignKey("organization_proposals.id", ondelete="CASCADE"), primary_key=True),
    Column("resident_id", ForeignKey("residents.id", ondelete="RESTRICT"), primary_key=True),
    Column("decision", String(16), nullable=False),
    Column("vote_weight", Integer, nullable=False),
    Column("rationale", Text, nullable=False, default=""),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("decision IN ('approve', 'reject')", name="organization_votes_decision_valid"),
    CheckConstraint("vote_weight > 0", name="organization_votes_weight_positive"),
)

organization_commitments = Table(
    "organization_commitments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("commitment_key", String(200), nullable=False, unique=True),
    Column("organization_id", ForeignKey("campus_organizations.id", ondelete="RESTRICT"), nullable=False),
    Column("proposal_id", ForeignKey("organization_proposals.id", ondelete="SET NULL")),
    Column("commitment_type", String(64), nullable=False),
    Column("counterparty_actor_key", String(120), nullable=False, default=""),
    Column("amount_minor", BigInteger, nullable=False, default=0),
    Column("due_at", String(64), nullable=False, default=""),
    Column("status", String(16), nullable=False, default="active"),
    Column("responsibility_resident_id", ForeignKey("residents.id", ondelete="SET NULL")),
    Column("metadata_json", Text, nullable=False, default="{}"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("resolved_at", String(64), nullable=False, default=""),
    CheckConstraint("amount_minor >= 0", name="organization_commitments_amount_nonnegative"),
    CheckConstraint("status IN ('active', 'fulfilled', 'breached', 'cancelled')", name="organization_commitments_status_valid"),
)

organization_relationships = Table(
    "organization_relationships",
    metadata,
    Column("from_organization_id", ForeignKey("campus_organizations.id", ondelete="CASCADE"), primary_key=True),
    Column("to_organization_id", ForeignKey("campus_organizations.id", ondelete="CASCADE"), primary_key=True),
    Column("relation_type", String(24), nullable=False, default="neutral"),
    Column("trust", Integer, nullable=False, default=50),
    Column("influence", Integer, nullable=False, default=0),
    Column("status", String(16), nullable=False, default="active"),
    Column("evidence_json", Text, nullable=False, default="[]"),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("from_organization_id <> to_organization_id", name="organization_relationships_distinct"),
    CheckConstraint("relation_type IN ('neutral', 'alliance', 'service', 'competition', 'conflict')", name="organization_relationships_type_valid"),
    CheckConstraint("trust BETWEEN 0 AND 100", name="organization_relationships_trust_valid"),
    CheckConstraint("influence BETWEEN -100 AND 100", name="organization_relationships_influence_valid"),
    CheckConstraint("status IN ('active', 'inactive')", name="organization_relationships_status_valid"),
)

organization_events = Table(
    "organization_events",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("event_key", String(200), nullable=False, unique=True),
    Column("organization_id", ForeignKey("campus_organizations.id", ondelete="CASCADE"), nullable=False),
    Column("proposal_id", ForeignKey("organization_proposals.id", ondelete="SET NULL")),
    Column("event_type", String(64), nullable=False),
    Column("severity", String(16), nullable=False, default="info"),
    Column("details_json", Text, nullable=False, default="{}"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("severity IN ('info', 'warning', 'critical')", name="organization_events_severity_valid"),
)
