MARKET_RUNTIME_SQL = """
CREATE TABLE IF NOT EXISTS market_mechanisms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mechanism_key TEXT NOT NULL UNIQUE,
    item_id INTEGER NOT NULL,
    provider_actor_key TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT '',
    pricing_mode TEXT NOT NULL,
    base_price_minor INTEGER NOT NULL,
    floor_price_minor INTEGER NOT NULL,
    ceiling_price_minor INTEGER NOT NULL,
    variable_cost_minor INTEGER NOT NULL DEFAULT 0,
    target_supply INTEGER NOT NULL DEFAULT 1,
    target_daily_demand INTEGER NOT NULL DEFAULT 1,
    adjustment_rate_basis_points INTEGER NOT NULL DEFAULT 2500,
    demand_elasticity_basis_points INTEGER NOT NULL DEFAULT 10000,
    search_cost_minor INTEGER NOT NULL DEFAULT 0,
    transaction_cost_minor INTEGER NOT NULL DEFAULT 0,
    daily_quota_per_resident INTEGER NOT NULL DEFAULT 0,
    rule_version TEXT NOT NULL DEFAULT 'market-pricing-v1',
    status TEXT NOT NULL DEFAULT 'active',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (item_id, provider_actor_key, location),
    FOREIGN KEY (item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT,
    CHECK (pricing_mode IN ('fixed', 'dynamic', 'rationed', 'negotiated')),
    CHECK (base_price_minor >= 0),
    CHECK (floor_price_minor >= 0),
    CHECK (ceiling_price_minor >= floor_price_minor),
    CHECK (base_price_minor BETWEEN floor_price_minor AND ceiling_price_minor),
    CHECK (variable_cost_minor >= 0),
    CHECK (target_supply > 0),
    CHECK (target_daily_demand > 0),
    CHECK (adjustment_rate_basis_points BETWEEN 0 AND 10000),
    CHECK (demand_elasticity_basis_points BETWEEN 0 AND 30000),
    CHECK (search_cost_minor >= 0 AND transaction_cost_minor >= 0),
    CHECK (daily_quota_per_resident >= 0),
    CHECK (status IN ('active', 'paused'))
);

CREATE TABLE IF NOT EXISTS market_price_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quote_key TEXT NOT NULL UNIQUE,
    mechanism_id INTEGER NOT NULL,
    price_minor INTEGER NOT NULL,
    base_price_minor INTEGER NOT NULL,
    variable_cost_minor INTEGER NOT NULL DEFAULT 0,
    inventory_pressure_basis_points INTEGER NOT NULL DEFAULT 0,
    demand_pressure_basis_points INTEGER NOT NULL DEFAULT 0,
    environment_pressure_basis_points INTEGER NOT NULL DEFAULT 0,
    applied_adjustment_basis_points INTEGER NOT NULL DEFAULT 0,
    search_cost_minor INTEGER NOT NULL DEFAULT 0,
    transaction_cost_minor INTEGER NOT NULL DEFAULT 0,
    available_supply INTEGER NOT NULL DEFAULT 0,
    observed_demand INTEGER NOT NULL DEFAULT 0,
    fulfilled_demand INTEGER NOT NULL DEFAULT 0,
    rationed INTEGER NOT NULL DEFAULT 0,
    explanation TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    valid_until TEXT NOT NULL,
    state_fingerprint TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (mechanism_id) REFERENCES market_mechanisms(id) ON DELETE CASCADE,
    CHECK (price_minor >= 0),
    CHECK (base_price_minor >= 0 AND variable_cost_minor >= 0),
    CHECK (search_cost_minor >= 0 AND transaction_cost_minor >= 0),
    CHECK (available_supply >= 0 AND observed_demand >= 0 AND fulfilled_demand >= 0),
    CHECK (rationed IN (0, 1))
);

CREATE TABLE IF NOT EXISTS market_demand_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_key TEXT NOT NULL UNIQUE,
    resident_id INTEGER NOT NULL,
    mechanism_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    action_execution_id INTEGER,
    quantity INTEGER NOT NULL DEFAULT 1,
    need_score INTEGER NOT NULL DEFAULT 50,
    preference_score INTEGER NOT NULL DEFAULT 50,
    social_influence_score INTEGER NOT NULL DEFAULT 0,
    disposable_budget_minor INTEGER NOT NULL DEFAULT 0,
    maximum_unit_price_minor INTEGER NOT NULL DEFAULT 0,
    quoted_unit_price_minor INTEGER NOT NULL DEFAULT 0,
    final_unit_price_minor INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    substitute_item_id INTEGER,
    reason TEXT NOT NULL DEFAULT '',
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    FOREIGN KEY (mechanism_id) REFERENCES market_mechanisms(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT,
    FOREIGN KEY (substitute_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL,
    FOREIGN KEY (action_execution_id) REFERENCES world_action_executions(id) ON DELETE SET NULL,
    CHECK (quantity > 0),
    CHECK (need_score BETWEEN 0 AND 100),
    CHECK (preference_score BETWEEN 0 AND 100),
    CHECK (social_influence_score BETWEEN 0 AND 100),
    CHECK (disposable_budget_minor >= 0),
    CHECK (maximum_unit_price_minor >= 0),
    CHECK (quoted_unit_price_minor >= 0 AND final_unit_price_minor >= 0),
    CHECK (status IN ('accepted', 'fulfilled', 'price_rejected', 'substituted', 'deferred', 'out_of_stock', 'rationed'))
);

CREATE TABLE IF NOT EXISTS market_friction_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_key TEXT NOT NULL UNIQUE,
    mechanism_id INTEGER NOT NULL,
    resident_id INTEGER,
    demand_signal_id INTEGER,
    friction_type TEXT NOT NULL,
    monetary_cost_minor INTEGER NOT NULL DEFAULT 0,
    wait_minutes INTEGER NOT NULL DEFAULT 0,
    details_json TEXT NOT NULL DEFAULT '{}',
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (mechanism_id) REFERENCES market_mechanisms(id) ON DELETE CASCADE,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE SET NULL,
    FOREIGN KEY (demand_signal_id) REFERENCES market_demand_signals(id) ON DELETE SET NULL,
    CHECK (friction_type IN ('search_cost', 'transaction_cost', 'stockout', 'rationing', 'queue', 'information_gap', 'substitution')),
    CHECK (monetary_cost_minor >= 0 AND wait_minutes >= 0)
);

CREATE INDEX IF NOT EXISTS idx_market_mechanisms_item ON market_mechanisms(item_id, provider_actor_key);
CREATE INDEX IF NOT EXISTS idx_market_prices_mechanism_time ON market_price_snapshots(mechanism_id, valid_from);
CREATE INDEX IF NOT EXISTS idx_market_demand_mechanism_time ON market_demand_signals(mechanism_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_market_demand_resident_time ON market_demand_signals(resident_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_market_friction_time ON market_friction_events(mechanism_id, occurred_at);
"""
