CREDIT_RUNTIME_SQL = """
CREATE TABLE IF NOT EXISTS savings_goals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    goal_key TEXT NOT NULL UNIQUE,
    resident_id INTEGER NOT NULL,
    goal_type TEXT NOT NULL,
    target_amount_minor INTEGER NOT NULL,
    current_amount_minor INTEGER NOT NULL DEFAULT 0,
    target_date TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 70,
    status TEXT NOT NULL DEFAULT 'active',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    CHECK (goal_type IN ('emergency_reserve', 'education', 'purchase', 'general')),
    CHECK (target_amount_minor > 0 AND current_amount_minor >= 0),
    CHECK (priority BETWEEN 0 AND 100),
    CHECK (status IN ('active', 'achieved', 'paused', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS household_risk_profiles (
    resident_id INTEGER PRIMARY KEY,
    income_volatility INTEGER NOT NULL DEFAULT 50,
    health_exposure INTEGER NOT NULL DEFAULT 30,
    essential_cost_exposure INTEGER NOT NULL DEFAULT 40,
    shock_sensitivity INTEGER NOT NULL DEFAULT 50,
    mutual_aid_enrolled INTEGER NOT NULL DEFAULT 1,
    coverage_basis_points INTEGER NOT NULL DEFAULT 3000,
    coverage_limit_minor INTEGER NOT NULL DEFAULT 3000,
    risk_score INTEGER NOT NULL DEFAULT 50,
    status TEXT NOT NULL DEFAULT 'active',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    CHECK (income_volatility BETWEEN 0 AND 100),
    CHECK (health_exposure BETWEEN 0 AND 100),
    CHECK (essential_cost_exposure BETWEEN 0 AND 100),
    CHECK (shock_sensitivity BETWEEN 0 AND 100),
    CHECK (mutual_aid_enrolled IN (0, 1)),
    CHECK (coverage_basis_points BETWEEN 0 AND 10000),
    CHECK (coverage_limit_minor >= 0),
    CHECK (risk_score BETWEEN 0 AND 100),
    CHECK (status IN ('active', 'paused'))
);

CREATE TABLE IF NOT EXISTS economic_shocks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shock_key TEXT NOT NULL UNIQUE,
    resident_id INTEGER NOT NULL,
    shock_type TEXT NOT NULL,
    severity INTEGER NOT NULL,
    amount_minor INTEGER NOT NULL,
    cash_used_minor INTEGER NOT NULL DEFAULT 0,
    savings_used_minor INTEGER NOT NULL DEFAULT 0,
    risk_pool_paid_minor INTEGER NOT NULL DEFAULT 0,
    credit_used_minor INTEGER NOT NULL DEFAULT 0,
    uncovered_minor INTEGER NOT NULL DEFAULT 0,
    impact_score INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending',
    source_type TEXT NOT NULL DEFAULT 'credit_runtime',
    source_id TEXT NOT NULL DEFAULT '',
    occurred_at TEXT NOT NULL,
    settled_at TEXT NOT NULL DEFAULT '',
    details_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    CHECK (shock_type IN ('income_loss', 'medical', 'essential_repair', 'family_emergency')),
    CHECK (severity BETWEEN 1 AND 100),
    CHECK (amount_minor > 0),
    CHECK (cash_used_minor >= 0 AND savings_used_minor >= 0),
    CHECK (risk_pool_paid_minor >= 0 AND credit_used_minor >= 0),
    CHECK (uncovered_minor >= 0),
    CHECK (impact_score BETWEEN 0 AND 100),
    CHECK (status IN ('pending', 'settled', 'partially_covered', 'uncovered'))
);

CREATE TABLE IF NOT EXISTS risk_pool_claims (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    claim_key TEXT NOT NULL UNIQUE,
    shock_id INTEGER NOT NULL UNIQUE,
    resident_id INTEGER NOT NULL,
    requested_minor INTEGER NOT NULL,
    approved_minor INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    ledger_transaction_id INTEGER,
    reason TEXT NOT NULL DEFAULT '',
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shock_id) REFERENCES economic_shocks(id) ON DELETE CASCADE,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    FOREIGN KEY (ledger_transaction_id) REFERENCES ledger_transactions(id) ON DELETE SET NULL,
    CHECK (requested_minor > 0 AND approved_minor >= 0),
    CHECK (approved_minor <= requested_minor),
    CHECK (status IN ('approved', 'partial', 'rejected'))
);

CREATE TABLE IF NOT EXISTS credit_products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    lender_actor_key TEXT NOT NULL,
    product_type TEXT NOT NULL,
    min_principal_minor INTEGER NOT NULL,
    max_principal_minor INTEGER NOT NULL,
    annual_interest_basis_points INTEGER NOT NULL,
    penalty_interest_basis_points INTEGER NOT NULL DEFAULT 0,
    term_days INTEGER NOT NULL,
    payment_cadence_days INTEGER NOT NULL,
    grace_days INTEGER NOT NULL DEFAULT 3,
    minimum_credit_score INTEGER NOT NULL DEFAULT 500,
    collateral_required INTEGER NOT NULL DEFAULT 0,
    guarantor_allowed INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    rule_version TEXT NOT NULL DEFAULT 'household-credit-v1',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (product_type IN ('emergency', 'consumer', 'relationship')),
    CHECK (min_principal_minor > 0 AND max_principal_minor >= min_principal_minor),
    CHECK (annual_interest_basis_points BETWEEN 0 AND 10000),
    CHECK (penalty_interest_basis_points BETWEEN 0 AND 30000),
    CHECK (term_days > 0 AND payment_cadence_days > 0),
    CHECK (grace_days >= 0),
    CHECK (minimum_credit_score BETWEEN 300 AND 850),
    CHECK (collateral_required IN (0, 1) AND guarantor_allowed IN (0, 1)),
    CHECK (status IN ('active', 'paused', 'retired'))
);

CREATE TABLE IF NOT EXISTS credit_profiles (
    resident_id INTEGER PRIMARY KEY,
    credit_score INTEGER NOT NULL DEFAULT 600,
    credit_limit_minor INTEGER NOT NULL DEFAULT 0,
    outstanding_principal_minor INTEGER NOT NULL DEFAULT 0,
    accrued_interest_minor INTEGER NOT NULL DEFAULT 0,
    delinquency_count INTEGER NOT NULL DEFAULT 0,
    default_count INTEGER NOT NULL DEFAULT 0,
    last_review_date TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    CHECK (credit_score BETWEEN 300 AND 850),
    CHECK (credit_limit_minor >= 0),
    CHECK (outstanding_principal_minor >= 0),
    CHECK (outstanding_principal_minor <= credit_limit_minor),
    CHECK (accrued_interest_minor >= 0),
    CHECK (delinquency_count >= 0 AND default_count >= 0),
    CHECK (status IN ('active', 'restricted', 'defaulted', 'closed'))
);

CREATE TABLE IF NOT EXISTS credit_contracts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    contract_key TEXT NOT NULL UNIQUE,
    product_id INTEGER NOT NULL,
    borrower_resident_id INTEGER NOT NULL,
    lender_actor_key TEXT NOT NULL,
    guarantor_resident_id INTEGER,
    principal_minor INTEGER NOT NULL,
    outstanding_principal_minor INTEGER NOT NULL,
    accrued_interest_minor INTEGER NOT NULL DEFAULT 0,
    annual_interest_basis_points INTEGER NOT NULL,
    penalty_interest_basis_points INTEGER NOT NULL DEFAULT 0,
    originated_at TEXT NOT NULL,
    maturity_date TEXT NOT NULL,
    next_due_date TEXT NOT NULL,
    last_accrual_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    collateral_json TEXT NOT NULL DEFAULT '{}',
    ledger_transaction_id INTEGER NOT NULL,
    defaulted_at TEXT NOT NULL DEFAULT '',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES credit_products(id) ON DELETE RESTRICT,
    FOREIGN KEY (borrower_resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    FOREIGN KEY (guarantor_resident_id) REFERENCES residents(id) ON DELETE SET NULL,
    FOREIGN KEY (ledger_transaction_id) REFERENCES ledger_transactions(id) ON DELETE RESTRICT,
    CHECK (principal_minor > 0),
    CHECK (outstanding_principal_minor >= 0 AND outstanding_principal_minor <= principal_minor),
    CHECK (accrued_interest_minor >= 0),
    CHECK (annual_interest_basis_points BETWEEN 0 AND 10000),
    CHECK (penalty_interest_basis_points BETWEEN 0 AND 30000),
    CHECK (status IN ('active', 'late', 'defaulted', 'paid', 'restructured'))
);

CREATE TABLE IF NOT EXISTS credit_installments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    installment_key TEXT NOT NULL UNIQUE,
    contract_id INTEGER NOT NULL,
    sequence_number INTEGER NOT NULL,
    due_date TEXT NOT NULL,
    principal_due_minor INTEGER NOT NULL,
    interest_due_minor INTEGER NOT NULL DEFAULT 0,
    penalty_due_minor INTEGER NOT NULL DEFAULT 0,
    principal_paid_minor INTEGER NOT NULL DEFAULT 0,
    interest_paid_minor INTEGER NOT NULL DEFAULT 0,
    penalty_paid_minor INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'scheduled',
    paid_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contract_id) REFERENCES credit_contracts(id) ON DELETE CASCADE,
    UNIQUE (contract_id, sequence_number),
    CHECK (sequence_number > 0),
    CHECK (principal_due_minor > 0),
    CHECK (interest_due_minor >= 0 AND penalty_due_minor >= 0),
    CHECK (principal_paid_minor >= 0 AND interest_paid_minor >= 0 AND penalty_paid_minor >= 0),
    CHECK (principal_paid_minor <= principal_due_minor),
    CHECK (interest_paid_minor <= interest_due_minor),
    CHECK (penalty_paid_minor <= penalty_due_minor),
    CHECK (status IN ('scheduled', 'due', 'partial', 'paid', 'late', 'defaulted'))
);

CREATE TABLE IF NOT EXISTS credit_payments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_key TEXT NOT NULL UNIQUE,
    contract_id INTEGER NOT NULL,
    installment_id INTEGER,
    borrower_resident_id INTEGER NOT NULL,
    principal_minor INTEGER NOT NULL DEFAULT 0,
    interest_minor INTEGER NOT NULL DEFAULT 0,
    penalty_minor INTEGER NOT NULL DEFAULT 0,
    total_minor INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'posted',
    ledger_transaction_id INTEGER NOT NULL,
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contract_id) REFERENCES credit_contracts(id) ON DELETE CASCADE,
    FOREIGN KEY (installment_id) REFERENCES credit_installments(id) ON DELETE SET NULL,
    FOREIGN KEY (borrower_resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    FOREIGN KEY (ledger_transaction_id) REFERENCES ledger_transactions(id) ON DELETE RESTRICT,
    CHECK (principal_minor >= 0 AND interest_minor >= 0 AND penalty_minor >= 0),
    CHECK (total_minor > 0),
    CHECK (total_minor = principal_minor + interest_minor + penalty_minor),
    CHECK (status IN ('posted', 'reversed'))
);

CREATE TABLE IF NOT EXISTS credit_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_key TEXT NOT NULL UNIQUE,
    resident_id INTEGER NOT NULL,
    contract_id INTEGER,
    event_type TEXT NOT NULL,
    score_before INTEGER NOT NULL,
    score_after INTEGER NOT NULL,
    credit_limit_before_minor INTEGER NOT NULL DEFAULT 0,
    credit_limit_after_minor INTEGER NOT NULL DEFAULT 0,
    details_json TEXT NOT NULL DEFAULT '{}',
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE CASCADE,
    FOREIGN KEY (contract_id) REFERENCES credit_contracts(id) ON DELETE SET NULL,
    CHECK (event_type IN ('profile_created', 'loan_originated', 'interest_accrued', 'payment', 'late', 'default', 'restructured', 'limit_review')),
    CHECK (score_before BETWEEN 300 AND 850 AND score_after BETWEEN 300 AND 850),
    CHECK (credit_limit_before_minor >= 0 AND credit_limit_after_minor >= 0)
);

CREATE INDEX IF NOT EXISTS idx_savings_goals_resident ON savings_goals(resident_id, status);
CREATE INDEX IF NOT EXISTS idx_economic_shocks_resident ON economic_shocks(resident_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_credit_contracts_borrower ON credit_contracts(borrower_resident_id, status);
CREATE INDEX IF NOT EXISTS idx_credit_installments_due ON credit_installments(status, due_date);
CREATE INDEX IF NOT EXISTS idx_credit_payments_contract ON credit_payments(contract_id, id);
CREATE INDEX IF NOT EXISTS idx_credit_events_resident ON credit_events(resident_id, id);
"""
