-- Supabase/PostgreSQL schema for Campus Agent Simulation.
-- Paste this file into Supabase SQL Editor, or run it with psql.
-- JSON-like fields are intentionally kept as text because the current Python
-- code stores and parses JSON strings with json.dumps/json.loads.

create table if not exists residents (
    id integer generated by default as identity primary key,
    name text not null unique,
    role text not null,
    personality text not null,
    goal text not null,
    money integer not null default 100,
    location text not null,
    created_at text not null default current_timestamp
);

create table if not exists agent_profiles (
    resident_id integer primary key references residents(id) on delete cascade,
    gender text not null,
    avatar_style text not null,
    avatar_image text not null default '',
    hierarchy_level integer not null default 1,
    organization text not null default '学生',
    skills text not null default '{}',
    strategy text not null default '{}',
    energy integer not null default 80,
    time_budget integer not null default 100,
    mood text not null default '平稳',
    current_task text not null default '适应校园生活',
    schedule text not null default '[]',
    perception text not null default '{}'
);

create table if not exists inventory (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    item_name text not null,
    quantity integer not null default 0,
    unique(resident_id, item_name)
);

create table if not exists transactions (
    id integer generated by default as identity primary key,
    buyer_id integer not null references residents(id) on delete cascade,
    seller_id integer not null references residents(id) on delete cascade,
    item_name text not null,
    quantity integer not null,
    unit_price integer not null,
    total_price integer not null,
    created_at text not null default current_timestamp
);

create table if not exists relationships (
    from_resident_id integer not null references residents(id) on delete cascade,
    to_resident_id integer not null references residents(id) on delete cascade,
    score integer not null default 0,
    notes text not null default '',
    primary key (from_resident_id, to_resident_id)
);

create table if not exists policies (
    id integer generated by default as identity primary key,
    title text not null,
    description text not null,
    proposer_id integer not null references residents(id) on delete cascade,
    status text not null default 'voting',
    yes_votes integer not null default 0,
    no_votes integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists city_events (
    id integer generated by default as identity primary key,
    day integer not null default 1,
    event_type text not null,
    description text not null,
    created_at text not null default current_timestamp
);

create table if not exists memories (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    day integer not null default 1,
    content text not null,
    importance integer not null default 1,
    memory_type text not null default 'episodic',
    tags text not null default '',
    source text not null default 'action',
    last_accessed_at text not null default '',
    access_count integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists simulation_state (
    key text primary key,
    value text not null
);

create table if not exists agent_learning (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    day integer not null default 1,
    action text not null,
    outcome text not null,
    score_delta integer not null default 0,
    lesson text not null,
    created_at text not null default current_timestamp
);

create table if not exists collaborations (
    id integer generated by default as identity primary key,
    title text not null,
    leader_id integer not null references residents(id) on delete cascade,
    member_ids text not null default '[]',
    goal text not null,
    status text not null default 'active',
    score integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists competitions (
    id integer generated by default as identity primary key,
    title text not null,
    participant_ids text not null default '[]',
    metric text not null,
    winner_id integer references residents(id) on delete set null,
    result text not null,
    created_at text not null default current_timestamp
);

create table if not exists campus_state (
    day integer primary key,
    weather text not null default '晴',
    semester_stage text not null default '平时周',
    time_slot text not null default '上午',
    weekday text not null default '周一',
    temperature integer not null default 24,
    rainfall integer not null default 0,
    weather_source text not null default 'simulation',
    weather_observed_at text not null default '',
    real_date text not null default '',
    real_time text not null default '',
    time_source text not null default 'simulation',
    exam_pressure integer not null default 35,
    assignment_pressure integer not null default 40,
    study_atmosphere integer not null default 60,
    activity_heat integer not null default 50,
    event_name text not null default '社团招新',
    event_intensity integer not null default 50,
    campus_flow integer not null default 55,
    classroom_crowd integer not null default 55,
    canteen_crowd integer not null default 50,
    library_crowd integer not null default 45,
    dorm_crowd integer not null default 45,
    playground_crowd integer not null default 40,
    commercial_crowd integer not null default 50,
    traffic_status text not null default '正常',
    network_status text not null default '稳定',
    safety_level integer not null default 90,
    resource_pressure integer not null default 45,
    campus_mood text not null default '平稳',
    consumption_index real not null default 1.0,
    created_at text not null default current_timestamp
);

create table if not exists campus_spaces (
    code text primary key,
    name text not null,
    location text not null unique,
    capacity integer not null,
    open_hour integer not null,
    close_hour integer not null,
    status text not null default '开放',
    crowd_field text not null,
    purpose text not null,
    updated_at text not null default current_timestamp
);

create table if not exists campus_events (
    id integer generated by default as identity primary key,
    day integer not null,
    title text not null,
    event_type text not null,
    intensity integer not null default 50,
    target_spaces text not null default '[]',
    effects text not null default '{}',
    status text not null default 'active',
    created_at text not null default current_timestamp,
    resolved_at text
);

create table if not exists agent_news_posts (
    id integer generated by default as identity primary key,
    day integer not null,
    resident_id integer not null references residents(id) on delete cascade,
    headline text not null,
    content text not null,
    created_at text not null default current_timestamp,
    unique(day, resident_id)
);

create table if not exists external_information (
    id integer generated by default as identity primary key,
    title text not null unique,
    summary text not null,
    source_name text not null,
    source_url text not null default '',
    category text not null default 'general',
    relevance integer not null default 50,
    published_at text not null default '',
    created_at text not null default current_timestamp
);

create table if not exists agent_information (
    information_id integer not null references external_information(id) on delete cascade,
    resident_id integer not null references residents(id) on delete cascade,
    channel text not null,
    relevance integer not null default 50,
    credibility integer not null default 80,
    distortion_note text not null default '',
    source_resident_id integer references residents(id) on delete set null,
    received_at text not null default current_timestamp,
    primary key (information_id, resident_id)
);

create table if not exists relationship_dynamics (
    from_resident_id integer not null references residents(id) on delete cascade,
    to_resident_id integer not null references residents(id) on delete cascade,
    affinity integer not null default 50,
    trust integer not null default 50,
    cooperation integer not null default 50,
    competition integer not null default 0,
    conflict integer not null default 0,
    tension integer not null default 0,
    interaction_count integer not null default 0,
    last_day integer not null default 1,
    primary key (from_resident_id, to_resident_id)
);

create table if not exists long_term_goals (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    title text not null,
    category text not null default 'general',
    progress integer not null default 0,
    target_progress integer not null default 100,
    deadline_day integer not null default 14,
    status text not null default 'active',
    last_update_day integer not null default 1,
    created_at text not null default current_timestamp,
    completed_at text
);

create table if not exists group_goals (
    id integer generated by default as identity primary key,
    name text not null,
    group_type text not null default '临时小组',
    leader_id integer not null references residents(id) on delete cascade,
    member_ids text not null default '[]',
    roles text not null default '{}',
    shared_goal text not null,
    progress integer not null default 0,
    target_progress integer not null default 100,
    deadline_day integer not null default 14,
    status text not null default 'active',
    current_plan text not null default '',
    created_at text not null default current_timestamp
);

create table if not exists campus_organizations (
    id integer generated by default as identity primary key,
    name text not null unique,
    organization_type text not null,
    goal text not null,
    budget integer not null default 1000,
    resources text not null default '{}',
    schedule text not null default '[]',
    status text not null default 'active',
    created_at text not null default current_timestamp
);

create table if not exists organization_members (
    organization_id integer not null references campus_organizations(id) on delete cascade,
    resident_id integer not null references residents(id) on delete cascade,
    member_role text not null default 'member',
    joined_day integer not null default 1,
    status text not null default 'active',
    primary key (organization_id, resident_id)
);

create table if not exists simulation_action_logs (
    id integer generated by default as identity primary key,
    day integer not null,
    resident_id integer not null references residents(id) on delete cascade,
    perception text not null default '{}',
    retrieved_memories text not null default '[]',
    decision text not null default '{}',
    execution text not null default '{}',
    environment_feedback text not null default '{}',
    created_at text not null default current_timestamp
);

insert into simulation_state (key, value)
values ('current_day', '1'), ('campus_initialized', '0')
on conflict (key) do nothing;

insert into campus_spaces
    (code, name, location, capacity, open_hour, close_hour, status, crowd_field, purpose)
values
    ('dorm', '宿舍区', '宿舍区', 600, 0, 24, '开放', 'dorm_crowd', '休息、社交与夜间生活'),
    ('teaching', '教学楼', '教学楼', 450, 7, 22, '开放', 'classroom_crowd', '上课、小组讨论与实验'),
    ('library', '图书馆', '图书馆', 220, 8, 22, '开放', 'library_crowd', '自习、阅读与研究'),
    ('canteen', '食堂', '食堂', 300, 6, 21, '开放', 'canteen_crowd', '用餐与日常交流'),
    ('playground', '操场', '操场', 500, 6, 22, '开放', 'playground_crowd', '运动、训练与大型活动'),
    ('business', '商业街', '商业街', 180, 9, 22, '开放', 'commercial_crowd', '消费、创业与服务'),
    ('admin', '校务处', '校务处', 80, 8, 18, '开放', 'campus_flow', '通知、管理与政策协商')
on conflict (code) do nothing;

create index if not exists idx_agent_learning_resident_day on agent_learning(resident_id, day);
create index if not exists idx_agent_news_posts_day on agent_news_posts(day);
create index if not exists idx_campus_events_day_status on campus_events(day, status);
create index if not exists idx_city_events_day_id on city_events(day, id desc);
create index if not exists idx_external_information_category on external_information(category);
create index if not exists idx_group_goals_status_deadline on group_goals(status, deadline_day);
create index if not exists idx_memories_resident_day on memories(resident_id, day);
create index if not exists idx_simulation_action_logs_resident_day on simulation_action_logs(resident_id, day);
